# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coffee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coffee
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  target 'CoffeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoffeeUITests' do
    # Pods for testing
  end

end
